######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 16 12:39:31 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += textediter.h
FORMS += textediter.ui
SOURCES += main.cpp textediter.cpp
RESOURCES += mainwindow.qrc
